<?php

namespace Synduit\SynsocialDatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Synduit\SynsocialDatabaseBundle\Document\Domain;

/**
 * DomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends DocumentRepository
{
    public function createDomain($values) {
        $domain = new Domain();
        $domain->setName($values['name']);
        $domain->setCreated($values['date']);

        $this->prepareFields($domain, $values);

        $dm = $this->getDocumentManager();
        $dm->persist($domain);

        return $domain;
    }

    public function findDomain($domain_name)
    {
        return $this->findOneBy(
            array(
              'name' => $domain_name,
            )
        );
    }

    public function updateDomain($domain, $values) {
        $domain->setUpdated($values['date']);
        $this->prepareFields($domain, $values);
    }

    private function prepareFields(&$domain, $values) {
        $domain->setTimezone($values['timezone']);
    }
}
