<?php

namespace Synduit\SynsocialDatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Synduit\SynsocialDatabaseBundle\Document\Facebook;

/**
 * FacebookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookRepository extends DocumentRepository
{
    public function createFacebook($values)
    {
        $dm = $this->getDocumentManager();
        $facebook = new Facebook();
        $facebook->setDomain($values['domain']);

        $this->prepareFields($facebook, $values);

        $dm->persist($facebook);

        return $facebook;
    }

    public function updateFacebookToken($facebook, $values)
    {
        $this->prepareFields($facebook, $values);
    }

    private function prepareFields(&$facebook, $values) {
        if (isset($values['facebook_page_id'])) {
            $facebook->setPageId($values['facebook_page_id']);
        }
        if (isset($values['page_access_token'])) {
            $facebook->setPageAccessToken($values['page_access_token']);
        }
        if (isset($values['user_access_token'])) {
            $facebook->setUserAccessToken($values['user_access_token']);
        }
        if (isset($values['name'])) {
            $facebook->setName($values['name']);
        }
        if (isset($values['fb_id'])) {
            $facebook->setFbId($values['fb_id']);
        }
    }

    public function findFacebookByPageIdAndDomain($page_id, $domain)
    {
        return $this->findOneBy(
            array(
                    'pageId' => $page_id,
                    'domain' => $domain->getId(),
                )
        );
    }

    public function findFacebookByDomain($domain)
    {
        return $this->findOneBy(
            array(
                    'domain' => $domain->getId(),
                )
        );
    }

}
