<?php

namespace Synduit\SynsocialDatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Synduit\SynsocialDatabaseBundle\Document\Job;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends DocumentRepository
{
    public function createJob($values, $info) {
        $dm = $this->getDocumentManager();
        $jobs = array();
        foreach ($values as $value) {
            $job = new Job();
            $job->setDomain($value['domain']);

            if (isset($value['sourceId'])) {
                $job->setSourceId($value['sourceId']);
            }

            $job->setJobType($info['jobType']);
            $job->setStatus($info['status']);
            $job->setCreated(time());
            $dm->persist($job);
            $jobs[] = $job;
        }

        return $jobs;
    }

    public function updateJobStatus($job, $status, $options = array()) {
        $job->setStatus($status);
        $job->setUpdated(time());

        if (!empty($options['finished'])) {
            $job->setFinished($options['finished']);
        }
        if (!empty($options['started'])) {
            $job->setStarted($options['started']);
        }

        return $job;
    }

    public function findJobByStatus($status) {
        return $this->findOneBy(
            array(
              'status' => $status,
            )
        );
    }

    public function findJobByStatusAndType($status, $type) {
        return $this->findOneBy(
            array(
              'status' => $status,
              'jobType' => $type,
            )
        );
    }

    public function findJobBySourceId($sourceId) {
        return $this->findOneBy(
            array(
              'sourceId' => $sourceId,
            )
        );
    }

    public function createJobReports($job, $reports) {
        $job->setReports($reports);
        $job->setUpdated(time());
    }

}
