<?php

namespace Synduit\SynsocialDatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Synduit\SynsocialDatabaseBundle\Document\Setting;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends DocumentRepository
{

    public function set($key, $value)
    {
        $setting = $this->search();
        if (!$setting) {
            $setting = new Setting();
        }
        $function = 'set' . ucfirst($key);
        if (method_exists($setting, $function)) {
            $setting->$function($value);
            $dm = $this->getDocumentManager();
            $dm->persist($setting);
            $dm->flush();

            return true;
        }
        else {
            return false;
        }
    }

    public function get($key)
    {
        $setting = $this->search();
        $function = 'get' . ucfirst($key);
        if ($setting && method_exists($setting, $function)) {
            $value = $setting->$function();

            return $value;
        }
        else {
            return false;
        }
    }

    private function search()
    {
        $setting = $this->findAll();
        if (!empty($setting)) {
            return $setting[0];
        }
        else {
            return false;
        }
    }
}
